# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SteadybitDebug < Formula
  desc "Tool to gather debugging information from (on-premise) Steadybit platforms and agents"
  homepage "https://github.com/steadybit/steadybit-debug"
  version "1.3.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/steadybit/steadybit-debug/releases/download/v1.3.0/steadybit-debug_darwin_arm64.tar.gz"
      sha256 "b6c2fba3e030e97bae7dbbc913c2290f161d671120460bf2aad5b976f8ea1543"

      def install
        bin.install "steadybit-debug"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/steadybit/steadybit-debug/releases/download/v1.3.0/steadybit-debug_darwin_amd64.tar.gz"
      sha256 "0d1126fcce5630a5fc60bfddd830e0d7dc25db96bb6dbd431daed62da16d676f"

      def install
        bin.install "steadybit-debug"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/steadybit/steadybit-debug/releases/download/v1.3.0/steadybit-debug_linux_arm64.tar.gz"
      sha256 "29bd7afe951f683825e1ef75ee44bc7a8988c76c1b8aafa9de796aecf0552569"

      def install
        bin.install "steadybit-debug"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/steadybit/steadybit-debug/releases/download/v1.3.0/steadybit-debug_linux_amd64.tar.gz"
      sha256 "04ff0ab8352830de2532e68938c798f296644b54be3d4477638107f42735e725"

      def install
        bin.install "steadybit-debug"
      end
    end
  end
end
