# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SteadybitDebug < Formula
  desc "Tool to gather debugging information from (on-premise) Steadybit platforms and agents"
  homepage "https://github.com/steadybit/steadybit-debug"
  version "1.3.3"

  on_macos do
    on_intel do
      url "https://github.com/steadybit/steadybit-debug/releases/download/v1.3.3/steadybit-debug_darwin_amd64.tar.gz"
      sha256 "f703ff5cc78cbeadb2d0df3c7266a5d40482f69bc923e8d6610699b5d48f468a"

      def install
        bin.install "steadybit-debug"
      end
    end
    on_arm do
      url "https://github.com/steadybit/steadybit-debug/releases/download/v1.3.3/steadybit-debug_darwin_arm64.tar.gz"
      sha256 "aae1fc3dd086f6f9f2c9f5d37deb024e0d0f8b90bd9037eb94d133faea7eccc1"

      def install
        bin.install "steadybit-debug"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/steadybit/steadybit-debug/releases/download/v1.3.3/steadybit-debug_linux_amd64.tar.gz"
        sha256 "ec36dd316a3ab786cba7f981cd1d1114dda7c8fb49193d5d31bdff1db51154cf"

        def install
          bin.install "steadybit-debug"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/steadybit/steadybit-debug/releases/download/v1.3.3/steadybit-debug_linux_arm64.tar.gz"
        sha256 "41d091cdde06b6168805d2cb6552f75fbc2adbac852295f21a518b01e5bca032"

        def install
          bin.install "steadybit-debug"
        end
      end
    end
  end
end
